auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Hyper Hamster
url: xixi.group
feed: /atom.xml
author_info: <a href="http://mukosame.github.io/">XiXi</a>
